version: "3"
services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass 123456x
    networks:
      app-net:
  web:
    depends_on:
      - redis
    build:
      context: app
      dockerfile: app/Dockerfile
    container_name: webapp
    environment:
      ENV: DEBUG
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      app-net:
networks:
  app-net:
    driver: bridge

